apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-frontend-config
  labels:
    app: nginx-frontend
    tier: frontend
data:
  nginx.conf: |
    server {
        listen 80;
        server_name _;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Frontend Service</title>
    </head>
    <body>
        <h1>Welcome to Frontend Service</h1>
        <p>This is the frontend nginx deployment managed by kube-applier.</p>
    </body>
    </html>
