apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
  labels:
    app: flask-backend
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: flask-backend
