apiVersion: v1
kind: ConfigMap
metadata:
  name: python-backend-config
  labels:
    app: flask-backend
    tier: backend
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Backend Service</title>
    </head>
    <body>
        <h1>Backend Service</h1>
        <p>This is the Python backend deployment managed by kube-applier.</p>
        <p>Simple HTTP server running on port 8080</p>
        <p>Version: 6.0.0</p>
    </body>
    </html>
