apiVersion: v1
kind: Service
metadata:
  name: nodejs-monitoring-service
  labels:
    app: nodejs-monitoring
    tier: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: nodejs-monitoring
