apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-monitoring
  labels:
    app: nodejs-monitoring
    tier: monitoring
    version: "8.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-monitoring
  template:
    metadata:
      labels:
        app: nodejs-monitoring
        tier: monitoring
    spec:
      containers:
      - name: nodejs
        image: node:16-alpine
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONITORING_SERVICE
          value: "true"
        command: ["node", "-e", "const http=require('http');const fs=require('fs');const server=http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html'});res.end('<h1>Monitoring Service</h1><p>Node.js HTTP server running on port 3000</p><p>Version: 8.0.0</p>')});server.listen(3000,'0.0.0.0',()=>console.log('Server running on port 3000'))"]
