apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-monitoring
  labels:
    app: nodejs-monitoring
    tier: monitoring
    version: "10.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-monitoring
  template:
    metadata:
      labels:
        app: nodejs-monitoring
        tier: monitoring
        version: "10.0.0"
        build: "stable"
    spec:
      containers:
      - name: nodejs-server
        image: node:16-alpine
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: MONITORING_SERVICE
          value: "true"
        command: ["npx", "http-server", "-p", "3000", "-a", "0.0.0.0"]
