apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-monitoring-config
  labels:
    app: nodejs-monitoring
    tier: monitoring
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Monitoring Service</title>
    </head>
    <body>
        <h1>Monitoring Service</h1>
        <p>This is the Node.js monitoring deployment managed by kube-applier.</p>
        <p>Simple HTTP server running on port 3000</p>
        <p>Version: 8.0.0</p>
    </body>
    </html>
