apiVersion: v1
kind: Service
metadata:
  name: postgres-database-service
  labels:
    app: postgres-database
    tier: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres-database
